### ISSUE TITLE
invoke build-config-reference errors out

### ISSUE THREAD

**Issue by swallitsch** [AcademySoftwareFoundation/OpenColorIO-Config-ACES#27]
``` bash
OpenColorIO-Config-ACES]# invoke build-config-reference
===============================================================================
*                                                                             *
*   Building the "aces-dev" reference "OpenColorIO" config...                 *
*                                                                             *
===============================================================================
Traceback (most recent call last):
  File "config.py", line 1195, in <module>
    additional_data=True)
  File "/home/aswf/OpenColorIO-Config-ACES/opencolorio_config_aces/utilities/common.py", line 395, in wrapped
    return function(*args, **kwargs)
  File "config.py", line 941, in generate_config_aces
    classify_aces_ctl_transforms(discover_aces_ctl_transforms()))
  File "/home/aswf/OpenColorIO-Config-ACES/opencolorio_config_aces/config/reference/discover/classify.py", line 1272, in classify_aces_ctl_transforms
    *itertools.chain.from_iterable(unclassified_ctl_transforms.values()))
  File "/home/aswf/OpenColorIO-Config-ACES/opencolorio_config_aces/utilities/common.py", line 120, in paths_common_ancestor
    common_ancestor(*[path.split(os.sep) for path in args]))
  File "/home/aswf/OpenColorIO-Config-ACES/opencolorio_config_aces/utilities/common.py", line 93, in common_ancestor
    ancestor = min(args)
ValueError: min() arg is an empty sequence
```

**Comment by KelSolaar** [comment]
Out of curiosity, when you pulled the main repo, did you initialise the sub-modules, i.e. `git submodule update --init --recursive` (We should add that to the docs)?

**Comment by swallitsch** [comment]
No, I was unaware that the repository made use of submodules. I'll try that and report back.

**Comment by swallitsch** [comment]
Sorry for the late reporting- this worked and was my issue
